name: mot_neural_solver
channels:
  - pytorch
  - conda-forge
  - soumith
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - blas=1.0=mkl
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cloudpickle=1.4.1=py_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.17.0=py_0
  - decorator=4.4.2=py_0
  - freetype=2.10.2=he06d7ca_0
  - icu=64.2=he1b5a44_1
  - imagecodecs-lite=2019.12.3=py36h8c4c3a4_0
  - imageio=2.8.0=py_0
  - intel-openmp=2019.4=243
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.2.0=py36hdb11119_0
  - ld_impl_linux-64=2.34=h53a641e_4
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libgomp=9.2.0=h24d8f2e_2
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libwebp-base=1.1.0=h516909a_3
  - lz4-c=1.9.2=he1b5a44_1
  - matplotlib-base=3.2.1=py36hb8e4980_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36h516909a_0
  - mkl_fft=1.1.0=py36hc1659b7_1
  - mkl_random=1.1.0=py36hb3f55d8_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_1
  - ninja=1.10.0=hc9558a2_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - pillow=7.1.2=py36h8328e55_0
  - pip=20.1.1=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.6.10=h8356626_1011_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.5.0=py3.6_cuda10.1.243_cudnn7.6.3_0
  - pywavelets=1.1.1=py36h785e9b2_1
  - readline=8.0=hf8c457e_0
  - scikit-image=0.17.2=py36h830a2c2_0
  - scipy=1.4.1=py36h0b6359f_0
  - setuptools=46.4.0=py36h9f0ad1d_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.30.1=hcee41ef_0
  - tifffile=2020.5.11=py_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - torchvision=0.6.0=py36_cu101
  - tornado=6.0.4=py36h8c4c3a4_1
  - wheel=0.34.2=py_1
  - xz=5.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - absl-py==0.9.0
    - ase==3.19.1
    - attrs==19.3.0
    - backcall==0.1.0
    - cachetools==4.1.0
    - chardet==3.0.4
    - colorama==0.4.3
    - docopt==0.6.2
    - easydict==1.9
    - flake8==3.8.2
    - flake8-import-order==0.18.1
    - future==0.18.2
    - gitdb==4.0.5
    - gitpython==3.1.2
    - google-auth==1.15.0
    - google-auth-oauthlib==0.4.1
    - googledrivedownloader==0.4
    - grpcio==1.29.0
    - h5py==2.10.0
    - hydra-core==0.11.3
    - idna==2.9
    - importlib-metadata==1.6.0
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - isodate==0.6.0
    - jedi==0.17.0
    - joblib==0.15.1
    - jsonpickle==1.4.1
    - lapsolver==1.1.0
    - llvmlite==0.32.1
    - markdown==3.2.2
    - mccabe==0.6.1
    - more-itertools==8.3.0
    - motmetrics==1.2.0
    - munch==2.5.0
    - numba==0.49.1
    - oauthlib==3.1.0
    - omegaconf==1.4.1
    - opencv-python==4.2.0.34
    - packaging==20.4
    - pandas==1.0.3
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pluggy==0.13.1
    - plyfile==0.7.2
    - prompt-toolkit==3.0.5
    - protobuf==3.12.2
    - ptyprocess==0.6.0
    - pulp==2.1
    - py==1.8.1
    - py-cpuinfo==5.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.6.0
    - pyflakes==2.2.0
    - pygments==2.6.1
    - pytest==5.4.2
    - pytest-benchmark==3.2.3
    - pytorch-lightning==0.7.6
    - pytz==2020.1
    - pyyaml==5.3.1
    - rdflib==5.0.0
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - sacred==0.8.1
    - scikit-learn==0.23.1
    - smmap==3.0.4
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - threadpoolctl==2.0.0
    - -f https://pytorch-geometric.com/whl/torch-1.5.0.html
    - torch-cluster==1.5.4+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
    - torch-scatter==2.0.4+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
    - torch-sparse==0.6.4+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
    - torch-spline-conv==1.2.0+cu101 -f https://pytorch-geometric.com/whl/torch-1.5.0.html
    - torch-geometric==1.5.0
    - tqdm==4.46.0
    - traitlets==4.3.3
    - urllib3==1.25.9
    - wcwidth==0.1.9
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - xmltodict==0.12.0
    - zipp==3.1.0
